v2t:
  llava1.5_7b:
    pretrained: "/path/to/llava1.5_7b"
    arch: "llava"
    torch_dtype: "float16"
    layer: 32
  
  instructblip_vicuna_7b:
    pretrained: "/path/to/instructblip_vicuna_7b"
    arch: "instruct"
    torch_dtype: "float16"
    layer: 32
  
  llavanext_8b:
    pretrained: "/path/to/llama3-llava_next_8b_hf"
    arch: "llavanext"
    torch_dtype: "float16"
    layer: 32
    
classifier:
  roberta-base:
    pretrained: "/path/to/roberta-base"
    arch: "RobertaForMaskedLM"
    torch_dtype: "float16"
